version: '3'
services:
  payara-full:
    build: mypayara-full
    environment:
      - ADMIN_PASSWORD=admin
    ports:
      - "7070:7070"
      - "4848:4848"
    depends_on:
      - db


  db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db: